### ISSUE TITLE
unable to play .wav files on MS Windows

### ISSUE THREAD

**Issue by rogererens** [realpython/python-speech-recognition#1]
I am unable to open these .wav files on multiple PCs, trying multiple Music players, e.g. VLC Media Player, Groove Music, Windows Media Player, ITunes, and following your speech recognition article for python.
Can you provide files that can be used on MS Windows out of the box?
Here is the Groove Music error message:

![image](https://user-images.githubusercontent.com/907897/37762266-182074a2-2dbc-11e8-939a-65524fcd03cf.png)

**Comment by somacdivad** [comment]
These files were created in Windows and I tested them on Linux, mac OS and Windows. I guess it's possible they were corrupted when I uploaded them. I will check when I get off work today. You may also try downloading them again as it could be possible they were corrupted at that point.

**Comment by rogererens** [comment]
When I drill down in Github's web interface to
https://github.com/realpython/python-speech-recognition/blob/master/audio_files/harvard.wav
I get this Download button at the right hand side, and a 'View Raw' link (with a kind of error message) in the middle of the screen. Both end up giving me the above mentioned result of corrupt files when downloaded.
![image](https://user-images.githubusercontent.com/907897/37802628-94870c08-2e2b-11e8-8a01-73ba0943c3a1.png)

**But fortunately**, on the project page there's this green 'Clone or download' button, and after clicking that and choosing 'Download ZIP' I obtain a zip file which has the playable files after unpacking.
![image](https://user-images.githubusercontent.com/907897/37802707-dde532d0-2e2b-11e8-8dde-4052897c50a0.png)

Cloning the repo also results in .wav files that are OK to play (I should've tried this in the first place, of course).

So, it's probably some Github bug or limitation... non-intuitive, to say the least.

Thanks for your interesting article!
