### ISSUE TITLE
 *.wav file is corrupt

### ISSUE THREAD

**Issue by moonrich** [realpython/python-speech-recognition#2]
I can't to open  *.wav file, Please check

**Comment by somacdivad** [comment]
@merxer How did you download the WAV files? If you tried to download them directly, this may not work. Try cloning the repository or using the "Download as ZIP" option by clicking the green "Clone or Download" button on the main page:
![selection_009](https://user-images.githubusercontent.com/20980298/38456946-f131e8da-3a4f-11e8-93f8-c1873ccb30dc.png)

If you still have issues after trying those steps, please come back here and let me know!

**Comment by RajSharma1** [comment]
Thanks for your tutorial, it helped ! but I tried downloading the audio file and kept the file "harvard.wav" where the python launcher is, and also in Lib directory but still this is the error.


![image](https://user-images.githubusercontent.com/24774699/40643991-6a66b34e-633f-11e8-9a6a-72e7c5fe0370.png)

Here, i kept the file >>  "C:\Users\Dell\AppData\Local\Programs\Python\Python35-32"
and,  a copy in >>  "C:\Users\Dell\AppData\Local\Programs\Python\Python35-32\Lib"

Can you help me please !

**Comment by RajSharma1** [comment]
Thanks it is resolved ! I kept the file in the directory where i saved the python file and it worked.
