### ISSUE TITLE
OSError: No Default Input Device Available

### ISSUE THREAD

**Issue by Sanix-Darker** [realpython/python-speech-recognition#7]
Am getting this error when am trying to access my microphone! 
Am on Ubuntu dist!

**Comment by somacdivad** [comment]
Hi @Sanix-Darker, sorry for taking a couple of weeks to get to you here.

Did you ever resolve the problem?

If not, do you have a microphone on your device? Are you using Ubuntu on a laptop or something like a Raspberry Pi?

You may need to set a default microphone in your OS settings when trying to use the system default mic for recording.

**Comment by ghost** [comment]
Hi @Sanix-Darker  , this could be either an issue with your very microphone. Or, the program must not be able to recognize the microphone of your machine. You might want to update to latest drivers. If everything fails, then you can also specify the index of the microphone through which you want to give your command. For some, this may be 1, 2, or three etc. But for a vast majority of people, in majority cases it is generally 0.

**Comment by Sanix-Darker** [comment]
issue fixed with drivers updated !
Thanks for your feedbacks guys !
